name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Clean
        run: mvn -ntp clean
      - name: Build
        run: mvn -ntp compile
      - name: Short test
        run: mvn -ntp test -Dtest=CalculatorTest
      - name: Long test
        run: mvn -ntp test -Dtest=CalculatorTestThorough
