name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Echo Test
        run: echo this is a test